# Generated by Django 6.0.7 on 2026-07-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=50)),
                ('rows', models.PositiveIntegerField(help_text='Number of rows in seat grid')),
                ('columns', models.PositiveIntegerField(help_text='Number of columns in seat grid')),
                ('capacity', models.PositiveIntegerField(editable=False)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
