# Generated by Django 6.0.7 on 2026-07-15 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('session', models.CharField(choices=[('Morning', 'Morning (09:30 AM - 12:30 PM)'), ('Afternoon', 'Afternoon (02:00 PM - 05:00 PM)')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='timetables/')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='exams.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='subjects.subject')),
            ],
            options={
                'unique_together': {('exam', 'subject', 'exam_date', 'session')},
            },
        ),
    ]
